# -*- coding: utf-8 -*-
import time
import requests
import json
import click
import pandas as pd
import numpy as np
from datetime import datetime

__author__ = "Leon Schnieber"
__version__ = "1.0.1"
__maintainer__ = "Leon Schnieber"
__email__ = "leon@faler.ch"
__status__ = "Development"

@click.group()
def cli():
    pass

@cli.command()
@click.option("--inputFile", default="data/rawData.csv", help="CSV-File generated by schnieboard to read the raw data from")
def list_markers(inputfile):
    with open(inputfile, "r") as f:
        raw_rows = []
        marker_rows = []
        for row in f.readlines():
            if ">;" not in row and "#;" not in row:
                print(row.strip())

@cli.command()
@click.option("--influxBaseUrl", default="https://sensor:wd40@smartpouch.foobar.rocks/influx", help="URL to influx-server endpoint")
@click.option("--influxDatabase", default="master", help="Database-name of influx-server to write in")
@click.option("--influxTableName", default="schnieboard_meas", help="table name inside the influx-database, e.g. for debugging")
def delete_database(influxbaseurl, influxdatabase, influxtablename):
    q = input("Are you really really sure to delete the database? (type 'Y' and enter to continue.)")
    if "Y" not in q:
        print("aborted.")
        return 0
    params = {
        "db": influxdatabase,
        "q": f"DELETE FROM {influxtablename}"
    }
    try:
        response = requests.post(f"{influxbaseurl}/query", params=params)
        if response.status_code == 200:
            print("All values deleted successfully.")
        else:
            print(f"Error: {response.text}")
    except Exception as e:
        print(f"An error occurred: {e}")


@cli.command()
@click.option("--inputFile", help="CSV-File generated by schnieboard to read the raw data from")
@click.option("--startMarkerName", help="start marker name")
@click.option("--endMarkerName", help="end marker name")
@click.option("--startMarkerTime", help="YYYY-DD-MMTHH:MM:SS.ms (ISO-Time) where start marker is aligned to.")
@click.option("--addAnnotations", type=bool, default=True, help="add annotations to grafana. Grafana-Login needs to be placed in a config-file.")
@click.option("--influxBaseUrl", default="https://sensor:wd40@smartpouch.foobar.rocks/influx", help="URL to influx-server endpoint")
@click.option("--influxDatabase", default="master", help="Database-name of influx-server to write in")
@click.option("--influxTableName", default="schnieboard_meas", help="table name inside the influx-database, e.g. for debugging")
@click.option("--influxUploadBatchSize", default=1000, help="batch size for uploads (# of rows in one request)")
@click.option("--grafanaConfigfile", default="config.json", help="path to the config-file containing grafana-config-data")
@click.pass_context
def upload(ctx, inputfile, startmarkername, endmarkername, startmarkertime, addannotations, influxbaseurl, influxdatabase, influxtablename, influxuploadbatchsize, grafanaconfigfile):

    date_format = "%Y-%m-%dT%H:%M:%S.%f"
    dt_object = datetime.strptime(startmarkertime, date_format)
    startmarkertime_timestamp = dt_object.timestamp()

    read_filename = inputfile
    mode = -1
    offset_ticks = 0
    with open(read_filename, "r") as f:
        raw_rows = []
        for row in f.readlines():
            if ";meas;" in row and mode == -1:
                raw_rows.append(row.strip().split(";")) # get first row!
                mode = 0
            elif ";meas;" in row and mode == 1:
                offset_ticks = int(row.strip().split(";")[2])
                raw_rows.append(row.strip().split(";"))
                mode = 2
            elif ";meas;" in row and mode == 2:
                raw_rows.append(row.strip().split(";"))
            elif ">;" not in row:
                if row.strip() == startmarkername:
                    print("start marker found!")
                    mode = 1
                elif row.strip() == endmarkername:
                    mode = 3
                    print("end marker found!")
    if mode == 0:
        print("WARNING: no start marker was found. aborting.")
        return
    elif mode == 1:
        print("WARNING: no end marker was found. using data from start marker to EOF.")
    else:
        print(f"{len(raw_rows)} rows between the markers found. now uploading.")

    df = pd.DataFrame(raw_rows[1:])
    df = df.rename(columns=dict(zip(df.columns, raw_rows[0])))
    grafana_string = ""
    batch_limit = influxuploadbatchsize
    batchct = 0

    first_timestamp = 0
    last_timestamp = 0
    for index, row in df.iterrows():
        substr = ""
        for k in row.keys():
            if k not in ["#", "meas", "ticks", 18]:
                substr += f"{k}={row[k]},"
        try:
            time_str = startmarkertime_timestamp * 1e6 + int(row["ticks"]) * 1000 - offset_ticks * 1000
            if first_timestamp == 0:
                first_timestamp = time_str
        except:
            print("err", row)
        batchct += 1

        grafana_string += f"{influxtablename},sensor=pouch01,type=meas {substr.strip(',')} {round(time_str)}\n"
        if batchct >= batch_limit:
            r = requests.post(f"{influxbaseurl}/write?db={influxdatabase}&precision=u", grafana_string, timeout=10)
            if r.status_code >= 200 and r.status_code <= 299:
                print(f"\ruploading rows {index} / {df.shape[0]}", end="")
                grafana_string = ""
                batchct = 0
            else:
                print("req fail", r, r.text)
    # upload the remaining dataset-parts
    r = requests.post(f"{influxbaseurl}/write?db={influxdatabase}&precision=u", grafana_string, timeout=10)
    if r.status_code >= 200 and r.status_code <= 299:
        print(f"\ruploading rows {index} / {df.shape[0]}", end="")
        grafana_string = ""
        batchct = 0
    else:
        print("req fail", r, r.text)

    last_timestamp = time_str
    
    print("\rUpload complete!")
    if addannotations:
        print("Adding annotations…")
        grafana_string = f'{influxtablename}_annotation,sensor=pouch01,type=annotation title="{startmarkername}",description="" {round(first_timestamp)}\n'
        grafana_string += f'{influxtablename}_annotation,sensor=pouch01,type=annotation title="{endmarkername}",description="" {round(last_timestamp)}\n'
        r = requests.post(f"{influxbaseurl}/write?db={influxdatabase}&precision=u", grafana_string, timeout=10)
        if r.status_code >= 200 and r.status_code <= 299:
            print("annotations ok", r.text)
        else:
            print("annotation request fail", r, r.text)

if __name__ == "__main__":
    cli()
